### ISSUE TITLE
Mesh missing for blades and body of helicopter

### ISSUE THREAD

**Issue by iz05** [games50/helicopter#2]
Under the mesh filter category for blades, body, and skyscrapers, it says mesh is missing. For the helicopter itself, the animation is missing as well.

**Comment by geezlouisee** [comment]
Hi @iz05 , I initially encountered a similar issue as you. 

Steps I did to resolve the issue:
1. First, ensure Blender is installed first before opening the project in Unity
2. This is where I realised only the blades were open in my scene, but not the helicopter body/skyscrapers. I tried to right-click, in the Unity editor, any of the models located in `Assets/Resources/Models` and select the `Reimport All` option (as suggested in the project brief). However, that didn't work for me as well. 
3. Lastly, I managed to get the game running correctly by manually populating the mesh filters in each of the prefabs, as well as the helicopter gameObject in the hierarchy view. If you select the mesh option in the respective mesh filter components in the inspector views, a tab containing the different available meshes will be shown. Select the appropriate mesh when populating each prefab/helicopter gameObject, as shown below:
![ss](https://user-images.githubusercontent.com/39251616/83974961-8ba4bc00-a923-11ea-8b91-f73401169df3.png)

Not sure if there are better ways to resolve this issue but hope this helps in the meantime!

P.S. I'm using Unity 2019.2.21f1 and Blender 2.83

**Comment by iz05** [comment]
@geezlouisee thanks so much for your help! I installed Blender and selected the reimport all option, but I still have a problem.

When I click on the mesh filter option for each prefab, I still can't find the correct meshes. The only meshes that appear are the default ones. I attached a screenshot below. 

<img width="428" alt="problem" src="https://user-images.githubusercontent.com/64222861/84095463-640a2e00-a9cd-11ea-9fa7-c2cc9a79d097.PNG">

I was able to access the skyscrapers and helicopter in Blender. Do you know how I can attach them to the prefabs in Unity?

**Comment by geezlouisee** [comment]
Hi @iz05 , hmm unfortunately I'm unable to replicate the problem that you have :/ 

![image](https://user-images.githubusercontent.com/39251616/84172435-93dd3280-aaae-11ea-9512-bb3816ff577d.png)

The models should be under `Assets > Resources > Models` so if you don't see them there, perhaps you may have some missing files(?) Since you already have Blender installed, I think one way to go around this would just be to download the source files again and open a new project from scratch in Unity? But if the models are there, I suspect it might be incompatibility of the different versions of each software and you might need to update them accordingly. (I used Unity 2019.2.21f1 and Blender 2.83).

Hope this helps you!

**Comment by iz05** [comment]
@geezlouisee I installed a newer version of Unity and got it to work! Thank you so much for your help!
